### ISSUE TITLE
% as moisture unit_of_measurement

### ISSUE THREAD

**Issue by peterbarbosa** [volca/april-soil-esphome-module#2]
Hello,

Would anyone know the calculation to get the unit_of_measurement to be a % and what the correct formula would be?

**Comment by volca** [comment]
You can read two values for dry and put the sensor part into water. Let's say the previous one is the 0%, the last one is 100%. You can calculate the percent value depend the two values.

**Comment by peterbarbosa** [comment]
Any way to do that within sensor or will I need to do it within HA?

And any way to retain the value on MQTT/HA? Right now sensor shows as unavailable until next update.

**Comment by volca** [comment]
Please also check the [ESPhome for April Soil Moisture Sensor](https://github.com/illuzn/esphome-april-soil-moisture-sensor). It should match your requirements.

**Comment by peterbarbosa** [comment]
Yes, that seems to work. Still working on configuring the time to wake up, but using some of their code works great!
